In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import torch
import torch.nn as nn
from model import *
from data import *
from tools import *
from functions import *
import os



In [19]:
## Model parameters

gamma_c = 1
gamma_w = 0.99
eps = 1e-12
nu = 0.5
zeta = 1e-3


# Hyperparameters

T = 10000
K = 2
N = 3
size = 20

In [28]:
train_data = MyDatasetFolder('/workspace/TITAN/Unrolled-TITAN/TITAN_Unrolled/Datasets/train', K, N, size)

files in path:  ['X_A_46.pt', 'X_A_61.pt', 'X_A_68.pt', 'X_A_44.pt', 'X_A_89.pt', 'X_A_35.pt', 'X_A_21.pt', 'X_A_65.pt', 'X_A_66.pt', 'X_A_93.pt', 'X_A_23.pt', 'X_A_76.pt', 'X_A_53.pt', 'X_A_64.pt', 'X_A_45.pt', 'X_A_40.pt', 'X_A_78.pt', 'X_A_72.pt', 'X_A_8.pt', 'X_A_15.pt', 'X_A_98.pt', 'X_A_24.pt', 'X_A_3.pt', 'X_A_79.pt', 'X_A_0.pt', 'X_A_19.pt', 'X_A_42.pt', 'X_A_20.pt', 'X_A_7.pt', 'X_A_54.pt', 'X_A_49.pt', 'X_A_99.pt', 'X_A_50.pt', 'X_A_94.pt', 'X_A_14.pt', 'X_A_88.pt', 'X_A_6.pt', 'X_A_63.pt', 'X_A_9.pt', 'X_A_90.pt', 'X_A_43.pt', 'X_A_28.pt', 'X_A_55.pt', 'X_A_13.pt', 'X_A_58.pt', 'X_A_25.pt', 'X_A_16.pt', 'X_A_39.pt', 'X_A_91.pt', 'X_A_84.pt', 'X_A_96.pt', 'X_A_30.pt', 'X_A_69.pt', 'X_A_75.pt', 'X_A_52.pt', 'X_A_86.pt', 'X_A_71.pt', 'X_A_67.pt', 'X_A_92.pt', 'X_A_60.pt', 'X_A_29.pt', 'X_A_17.pt', 'X_A_2.pt', 'X_A_18.pt', 'X_A_5.pt', 'X_A_70.pt', 'X_A_4.pt', 'X_A_34.pt', 'X_A_73.pt', 'X_A_27.pt', 'X_A_85.pt', 'X_A_26.pt', 'X_A_51.pt', 'X_A_37.pt', 'X_A_80.pt', 'X_A_22.pt', 'X_A

In [29]:
train_loader = DataLoader(train_data, batch_size=4, shuffle=True)

In [30]:
for i, minibatch in enumerate(train_loader):
    print(i)
    print(minibatch)
    break

IndexError: list index out of range

In [47]:
train_data.__getitem__(19)

X_A_file:  /workspace/TITAN/Unrolled-TITAN/TITAN_Unrolled/Datasets/train/K_2_N_3/X_A_15.pt
X_A_item: (tensor([[[-0.8887,  0.6200],
         [-0.3165, -1.1356],
         [ 1.7150,  0.1094],
         ...,
         [-0.8613,  1.8470],
         [ 1.0364, -0.8503],
         [ 1.4469, -0.6369]],

        [[-1.6247, -0.0263],
         [-1.8629,  0.6149],
         [ 1.6266,  0.5973],
         ...,
         [ 1.1579,  0.1512],
         [-1.2259,  0.3307],
         [ 0.6852,  0.1613]],

        [[-0.2741, -0.3027],
         [ 0.1384,  0.4872],
         [ 0.3457,  0.2498],
         ...,
         [-0.8162, -1.0200],
         [ 0.4903,  0.5903],
         [ 0.5783,  1.2719]]], device='cuda:0'), tensor([[[ 0.3656,  0.5224],
         [ 0.3276, -0.3248],
         [ 0.7994, -0.7614]],

        [[ 0.8851,  0.7395],
         [-0.2699, -0.0498],
         [-0.2348,  0.6117]],

        [[-0.1538, -0.2289],
         [-0.7553, -0.9211],
         [ 0.4453,  0.2488]]], device='cuda:0'))


(tensor([[[-0.8887,  0.6200],
          [-0.3165, -1.1356],
          [ 1.7150,  0.1094],
          ...,
          [-0.8613,  1.8470],
          [ 1.0364, -0.8503],
          [ 1.4469, -0.6369]],
 
         [[-1.6247, -0.0263],
          [-1.8629,  0.6149],
          [ 1.6266,  0.5973],
          ...,
          [ 1.1579,  0.1512],
          [-1.2259,  0.3307],
          [ 0.6852,  0.1613]],
 
         [[-0.2741, -0.3027],
          [ 0.1384,  0.4872],
          [ 0.3457,  0.2498],
          ...,
          [-0.8162, -1.0200],
          [ 0.4903,  0.5903],
          [ 0.5783,  1.2719]]], device='cuda:0'),
 tensor([[[ 0.3656,  0.5224],
          [ 0.3276, -0.3248],
          [ 0.7994, -0.7614]],
 
         [[ 0.8851,  0.7395],
          [-0.2699, -0.0498],
          [-0.2348,  0.6117]],
 
         [[-0.1538, -0.2289],
          [-0.7553, -0.9211],
          [ 0.4453,  0.2488]]], device='cuda:0'))

In [13]:
torch.load('/workspace/TITAN/Unrolled-TITAN/TITAN_Unrolled/Datasets/val/K_2_N_3/X_A_0.pt')

(tensor([[[ 0.1286,  1.3134],
          [ 1.8020,  1.5249],
          [ 0.5853,  0.4089],
          ...,
          [ 0.5498, -0.6199],
          [ 2.3009,  1.1421],
          [-2.8176, -3.8359]],
 
         [[ 0.8670, -0.6903],
          [-0.1201, -0.5486],
          [-1.1090, -0.7122],
          ...,
          [-2.5448, -0.1329],
          [ 0.5270, -0.7207],
          [ 0.5625,  0.0045]],
 
         [[-0.3395, -1.2509],
          [-0.6506, -0.6952],
          [ 0.8248,  1.3844],
          ...,
          [ 0.5905,  0.1878],
          [-0.8695, -0.0417],
          [-0.2823,  1.6991]]], device='cuda:0'),
 tensor([[[ 0.2392,  0.0903],
          [-0.6304, -0.2377],
          [-0.6985, -0.9668]],
 
         [[ 0.6419,  0.3151],
          [ 0.7137,  0.9532],
          [-0.3027, -0.1853]],
 
         [[-0.6713, -0.8504],
          [ 0.4549,  0.3305],
          [-0.5119, -0.1708]]], device='cuda:0'))

In [5]:
X_A = torch.load('/workspace/TITAN/Unrolled-TITAN/TITAN_Unrolled/X_test1.pt')
A = torch.load('/workspace/TITAN/Unrolled-TITAN/TITAN_Unrolled/A_test2.pt')


In [5]:
Winit = torch.load('Winit.pt')
Cinit = torch.load('Cinit.pt')

X = X.unsqueeze(0)
A = A.unsqueeze(0)
Winit = Winit.unsqueeze(0)
Cinit = Cinit.unsqueeze(0)

NameError: name 'X' is not defined

In [6]:
X


tensor([[[-1.2570,  0.9512],
         [-0.2351, -0.4852],
         [-2.0252, -0.7628],
         ...,
         [ 0.0675,  0.5807],
         [ 1.0225,  1.4214],
         [ 1.5021, -0.9088]],

        [[-1.3847,  0.3959],
         [ 0.2829,  0.1645],
         [ 2.3373,  1.3782],
         ...,
         [-1.4743, -0.3040],
         [ 0.2067,  0.1120],
         [ 0.1923, -1.1541]],

        [[-0.3822,  1.1867],
         [ 0.0769,  0.6336],
         [ 0.7086, -0.3182],
         ...,
         [ 0.1473, -0.2113],
         [ 0.1956,  0.1571],
         [-0.6357, -1.9089]]], device='cuda:0')

In [7]:
X = X.unsqueeze(0)
A = A.unsqueeze(0)

In [8]:
input_dim = None
N_updates_W = 10
N_updates_C = 1
num_layers = 200
mode = 'end-to-end'
model = myModel(input_dim, N_updates_W, N_updates_C, num_layers=num_layers, gamma_c=gamma_c, gamma_w=gamma_w, eps=eps, nu=nu, zeta=zeta,B=1).cuda()

In [9]:
W_predicted,_ = model(X,A,mode)

In [10]:
W_predicted

tensor([[[[-0.1661, -1.0863],
          [-0.9151, -0.4016],
          [-0.6952, -0.0837]],

         [[-0.4319, -0.0690],
          [-0.5120,  0.3845],
          [ 0.7771, -0.9487]],

         [[ 1.1706, -0.4533],
          [-0.4709,  1.1241],
          [ 0.3402,  0.4885]]]], device='cuda:0', grad_fn=<PermuteBackward0>)

In [11]:
joint_isi(W_predicted[0], A[0])

tensor(0.4018, device='cuda:0', grad_fn=<DivBackward0>)

In [12]:
alpha = torch.ones(1).cuda()

In [30]:
alpha

tensor([1.], device='cuda:0')

In [14]:
coefficients = model.Layers[0].get_coefficients(cov_X(X),alpha,Cinit,Cinit)

In [15]:
c_w,_,_,_ = coefficients

In [19]:
c_w

tensor([0.3007], device='cuda:0')

In [17]:
prox_f(Winit,c_w)

s size:  torch.Size([1, 2, 3])
c_w size:  torch.Size([1])


tensor([[[[-0.1669,  0.9339],
          [-0.8453, -0.3444],
          [-0.7064,  0.6432]],

         [[-1.1260, -0.6793],
          [-0.0342, -1.1951],
          [ 0.1469,  0.2841]],

         [[-0.4657, -0.4355],
          [-0.5456,  1.9536],
          [ 0.7955,  0.2445]]]], device='cuda:0')

In [65]:
A

tensor([[[[ 0.6111,  0.6240],
          [ 0.8011, -0.6099],
          [ 0.1041,  0.4855]],

         [[-0.6772,  0.7226],
          [ 0.4255,  0.6575],
          [ 0.5905, -0.1225]],

         [[ 0.4432, -0.2338],
          [-0.4260,  0.4354],
          [ 0.8176,  0.8540]]]], device='cuda:0')

In [5]:
lambda_1 = 0.04
lambda_2 = 0.25
rho_bounds_1 = [0.2,0.3]
rho_bounds_2 = [0.6,0.7]
rhos = [rho_bounds_1,rho_bounds_2]
lambdas = [lambda_1,lambda_2]

metaparameters_multiparam = get_metaparameters(rhos,lambdas)
metaparameters_titles_multiparam = ['Case A','Case B','Case C','Case D']


X,A = generate_whitened_problem(T,K,N,epsilon=1,rho_bounds=rho_bounds_2,lambda_=lambda_1)
Winit = make_A(K,N)
Cinit = make_Sigma(K,N,rank=K+10)


In [8]:
X = X.unsqueeze(0)
A = A.unsqueeze(0)
Winit = Winit.unsqueeze(0)
Cinit = Cinit.unsqueeze(0)


In [52]:
print(f"Total GPU memory: {torch.cuda.get_device_properties(0).total_memory}")
print(f"Reserved GPU memory: {torch.cuda.memory_reserved()}")
print(f"Allocated GPU memory: {torch.cuda.memory_allocated()}")


Total GPU memory: 34089730048
Reserved GPU memory: 2097152
Allocated GPU memory: 448000


In [55]:
import torch
print("PyTorch version:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())
print("CUDA version:", torch.version.cuda)
print("CUDA device count:", torch.cuda.device_count())



PyTorch version: 1.11.0a0+bfe5ad2
CUDA available: True
CUDA version: 11.6
CUDA device count: 1


In [3]:
Cinit
c = 1
eps = 1e-3

In [24]:
C_perm = Cinit.permute(2, 0, 1)
s,U = torch.linalg.eigh(C_perm)
Vh = U.permute(0, 2, 1)
s_new = torch.maximum(torch.tensor(eps), (s + torch.sqrt(s**2 + 2 * c)) / 2)
# s_new = (s + np.sqrt(s**2+2*c_c))/2
diag_s = torch.diag_embed(s_new)  
C_new = torch.einsum('nNv,nvw,nwM -> nNM',U,diag_s,Vh)

In [25]:
C_new

tensor([[[1.3390, 0.3693],
         [0.3693, 1.4140]],

        [[1.4232, 0.4589],
         [0.4589, 1.3981]],

        [[1.3876, 0.5028],
         [0.5028, 1.2744]]], device='cuda:0')

In [33]:
C_perm = Cinit_batch.permute(0, 3, 1, 2)  # (batch, last_dim, height, width)
s, U = torch.linalg.eigh(C_perm)
Vh = U.transpose(-1, -2)
# Calculate the new singular values
s_new = torch.maximum(torch.tensor(eps), (s + torch.sqrt(s**2 + 2 * c)) / 2)
diag_s = torch.diag_embed(s_new)

# Reconstruct the matrix with the new singular values
C_new = torch.einsum('bnNv,bnvw,bnwM -> bnNM',U,diag_s,Vh)

In [35]:
Cinit_batch

tensor([[[[0.9366, 1.0303, 0.9671],
          [0.4744, 0.5879, 0.6687]],

         [[0.4744, 0.5879, 0.6687],
          [1.0329, 0.9981, 0.8166]]]], device='cuda:0')

In [37]:
C_perm

tensor([[[[0.9366, 0.4744],
          [0.4744, 1.0329]],

         [[1.0303, 0.5879],
          [0.5879, 0.9981]],

         [[0.9671, 0.6687],
          [0.6687, 0.8166]]]], device='cuda:0')

In [109]:
sym(C_new)

RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 1

In [40]:
prox_g_batch(Cinit_batch, c, eps)   

RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 3

In [41]:
Cinit.shape

torch.Size([2, 2, 3])

In [46]:
Cperm = Cinit_batch.permute(0, 3, 1, 2)

In [67]:
a,B = torch.linalg.eigh(Cinit.permute(2,0,1))

In [100]:
Bh = B.permute(0, 2, 1)
a_new = torch.maximum(torch.tensor(eps), (a + torch.sqrt(a**2 + 2 * c)) / 2)
# s_new = (s + np.sqrt(s**2+2*c_c))/2
diag_s = torch.diag_embed(a_new)  
A_new = torch.einsum('nNv,nvw,nwM -> nNM',B,diag_s,Bh)

In [102]:
A_new.permute(1, 2, 0)

tensor([[[1.3390, 1.4232, 1.3876],
         [0.3693, 0.4589, 0.5028]],

        [[0.3693, 0.4589, 0.5028],
         [1.4140, 1.3981, 1.2744]]], device='cuda:0')

In [69]:
a.shape

torch.Size([3, 2])

In [48]:
s,U = torch.linalg.eigh(Cperm)

In [66]:
s

tensor([[[0.5079, 1.4616],
         [0.4261, 1.6024],
         [0.2189, 1.5648]]], device='cuda:0')

In [76]:
x = (s + torch.sqrt(s**2 + 2 * c)) / 2

In [74]:
torch.tensor(eps)

tensor(0.0010)

In [78]:
x

tensor([[[1.0053, 1.7477],
         [0.9515, 1.8698],
         [0.8250, 1.8370]]], device='cuda:0')

In [83]:
s_new = torch.maximum(x, torch.tensor(eps))

In [85]:
s_new

tensor([[[1.0053, 1.7477],
         [0.9515, 1.8698],
         [0.8250, 1.8370]]], device='cuda:0')

In [90]:
diag_s = torch.diag_embed(s_new)

In [86]:
U

tensor([[[[ 0.7420,  0.6705],
          [-0.6705,  0.7420]],

         [[-0.6974,  0.7167],
          [ 0.7167,  0.6974]],

         [[-0.6664,  0.7456],
          [ 0.7456,  0.6664]]]], device='cuda:0')

In [96]:
C_new = torch.einsum('bnNv,bnvw,bnwM -> bnNM',U,diag_s,U.transpose(-1,-2))


In [98]:
C_new

tensor([[[[1.3390, 0.3693],
          [0.3693, 1.4140]],

         [[1.4232, 0.4589],
          [0.4589, 1.3981]],

         [[1.3876, 0.5028],
          [0.5028, 1.2744]]]], device='cuda:0')

In [97]:
C_new.permute(0, 2, 3, 1)

tensor([[[[1.3390, 1.4232, 1.3876],
          [0.3693, 0.4589, 0.5028]],

         [[0.3693, 0.4589, 0.5028],
          [1.4140, 1.3981, 1.2744]]]], device='cuda:0')

In [26]:
prox_g(Cinit, c, eps)

tensor([[[1.3390, 0.3693],
         [0.3693, 1.4140]],

        [[1.4232, 0.4589],
         [0.4589, 1.3981]],

        [[1.3876, 0.5028],
         [0.5028, 1.2744]]], device='cuda:0')

In [37]:
joint_isi(W_predicted,A)

tensor(0.0486, device='cuda:0', grad_fn=<DivBackward0>)

In [38]:
parameters = list(model.parameters())
print(parameters)

[Parameter containing:
tensor(1., device='cuda:0', requires_grad=True), Parameter containing:
tensor(1., device='cuda:0', requires_grad=True), Parameter containing:
tensor(1., device='cuda:0', requires_grad=True), Parameter containing:
tensor(1., device='cuda:0', requires_grad=True), Parameter containing:
tensor(1., device='cuda:0', requires_grad=True), Parameter containing:
tensor(1., device='cuda:0', requires_grad=True), Parameter containing:
tensor(1., device='cuda:0', requires_grad=True), Parameter containing:
tensor(1., device='cuda:0', requires_grad=True), Parameter containing:
tensor(1., device='cuda:0', requires_grad=True), Parameter containing:
tensor(1., device='cuda:0', requires_grad=True), Parameter containing:
tensor(1., device='cuda:0', requires_grad=True), Parameter containing:
tensor(1., device='cuda:0', requires_grad=True), Parameter containing:
tensor(1., device='cuda:0', requires_grad=True), Parameter containing:
tensor(1., device='cuda:0', requires_grad=True), Param

In [50]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset

In [61]:
class ToyNetwork(nn.Module):
    def __init__(self) -> None:
        super().__init__()
        self.fc1 = nn.Linear(2, 512)
    
    def forward(self, x):
        print(x.shape)
        x = self.fc1(x)
        return x

model = ToyNetwork()

In [60]:
nb_examples = 25
X = torch.randn(nb_examples,2)
X_alone = torch.randn(2)

In [64]:
model(X).shape

torch.Size([25, 2])


torch.Size([25, 512])

In [49]:
# Generate a toy dataset
def generate_toy_data(num_samples=1000):
    X = torch.randn(num_samples, 2)
    Y = torch.randn(num_samples, 512)  # Assuming the output should match the dimensions of the layer
    return X, Y

In [55]:

# Define training parameters
num_epochs = 10
batch_size = 32
learning_rate = 0.001

# Create dataset and dataloader
X, Y = generate_toy_data()
dataset = TensorDataset(X, Y)
dataloader = DataLoader(dataset, batch_size=batch_size, shuffle=True)

# Instantiate model, loss function, and optimizer
model = ToyNetwork()
criterion = nn.MSELoss()
optimizer = optim.Adam(model.parameters(), lr=learning_rate)


# Training loop
for epoch in range(num_epochs):
    epoch_loss = 0
    model.train()  # Set the model to training mode
    for batch in dataloader:
        inputs, targets = batch

        # Forward pass
        outputs = model(inputs)
        
        # Compute loss
        loss = criterion(outputs, targets)
        
        # Backward pass and optimization
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        # Accumulate loss
        epoch_loss += loss.item()

    # Average loss for the epoch
    avg_loss = epoch_loss / len(dataloader)
    print(f'Epoch [{epoch+1}/{num_epochs}], Loss: {avg_loss:.4f}')

Epoch [1/10], Loss: 1.4671
Epoch [2/10], Loss: 1.4158
Epoch [3/10], Loss: 1.3677
Epoch [4/10], Loss: 1.3296
Epoch [5/10], Loss: 1.2848
Epoch [6/10], Loss: 1.2510
Epoch [7/10], Loss: 1.2209
Epoch [8/10], Loss: 1.1952
Epoch [9/10], Loss: 1.1719
Epoch [10/10], Loss: 1.1469
